title: Laura's 100 Days of Code Blog
author: JB4706
email: info@LaBrightWebSolutions.com
description: > # this means to ignore newlines until "baseurl:"
  #100DaysofCode #R1D1 working on GitHub Pages in the GitHub Lab.  Just changed my theme, and added some boring text.

# social links
twitter_username: LaBrightWebSolu
github_username:  JB4706

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
